### ISSUE TITLE
Can I use it without css-modules?

### ISSUE THREAD

**Issue by Shyam-Chen** [mtojo/rollup-plugin-stylus-css-modules#2]
Angular 2 already provides the CSS modules.

**Comment by mtojo** [comment]
No, this plugin is intended to use the Stylus as a CSS modules.

If you need integrates Angular 2 and Stylus with Rollup.js, it might be solved by using [rollup-plugin-angular](https://github.com/cebor/rollup-plugin-angular):

```js
import angular from 'rollup-plugin-angular';
import stylus from 'stylus';

export default {
  entry: ...,
  format: 'iife',
  dest: ...,
  plugins: [
    angular({
      preprocessors: {
        style(source, filename) {
          const styl = stylus(source);
          styl.set('filename', filename);
          return await styl.render();
        }
      }
    })
  ]
}
```

See more details at: [https://github.com/cebor/rollup-plugin-angular#example-1](https://github.com/cebor/rollup-plugin-angular#example-1)
