### ISSUE TITLE
Importing multiple .styl files won't include all styles in generated CSS file

### ISSUE THREAD

**Issue by amireldor** [mtojo/rollup-plugin-stylus-css-modules#3]
My use case is having, for example, two components: App and NavBar. For keeping things tidy and organized I would like each to have its own Stylus file. Am I doing something funny and it should work out of the box?

In my App.js I would:

```js
import styles from './App.styl'
// now use styles.antelopes
```
Similary, in NavBar.js:
```js
import styles from './NavBar.styl'
// now use styles.unicorns
```

When I tried doing something like this I got styles from only one stylesheet, not both. When running rollup in watch-mode and changing a stylesheet file, the resulting CSS would reflect that stylesheet. If I saved the other one, the CSS now reflects the latter and the rules from the first one are gone.

The plugin should concatenate all the generated styles from the CSS modules, somehow making sure each module has truly unique entries per stylesheet. Moreover, it should somehow merge the sourcemaps from each generated module for the good and joy of the people of the world.

Notes: I already started hacking something to overcome this issue, but I barely get to working on it due to other responsibilities.

What do you say?

**Comment by mtojo** [comment]
Yes, there is only one stylesheet passed to `output`.

However, you can concatenate stylesheets as follows:

```js
import fs from 'fs';
import stylusCssModules from 'rollup-plugin-stylus-css-modules';

const styles = [];

export default {
  dest: '/path/to/destination.js',
  entry: '/path/to/source.js',
  plugins: [
    stylusCssModules({
      fn: (style) => {
        style.include('node_modules');
      },
      output: (css) => styles.push(css)
    })
    // ...
  ]
};

process.on('beforeExit', (code) => {
  if (code === 0) {
    fs.writeFileSync('/path/to/destination.css', styles.join('\n'));
  }
});
```

**Comment by mtojo** [comment]
I propose another method.

I added an option to cooperation with other CSS plugins. You can read multiple Stylus files, and export them to one CSS.

Use with [rollup-plugin-css-only](https://github.com/thgh/rollup-plugin-css-only) plugin:
```js
import stylusCssModules from 'rollup-plugin-stylus-css-modules';
import css from 'rollup-plugin-css-only';

export default {
  entry: 'index.js',
  plugins: [
    stylusCssModules(),
    css({
      output: 'bundle.css'
    })
  ]
};
```

Use with [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) plugin:
```js
import stylusCssModules from 'rollup-plugin-stylus-css-modules';
import postcss from 'rollup-plugin-postcss';

export default {
  entry: 'index.js',
  plugins: [
    stylusCssModules(),
    postcss({
      extract : 'bundle.css'
    })
  ]
};
```

**Comment by mtojo** [comment]
Closing this issue due to non response. Please re-open if this issue persists for you.
