### ISSUE TITLE
babel-runtime missing in dependencies

### ISSUE THREAD

**Issue by sebastian-lenz** [mtojo/rollup-plugin-stylus-css-modules#7]
In `dist/rollup-plugin-stylus-css-modules.es.js`and `dist/rollup-plugin-stylus-css-modules.cjs.js` babel-runtime is imported, but is not listed as a dependency in `package.json`.

**Comment by mtojo** [comment]
Thanks for feedback :-)
I have fixed deps and released as v1.4.1.
