### ISSUE TITLE
How to use it in typescript?

### ISSUE THREAD

**Issue by B1anker** [mtojo/rollup-plugin-stylus-css-modules#8]
When I used it in my project with typescript, there was an error occurred.But it worked in javascript.
![image](https://user-images.githubusercontent.com/17514962/32757789-eae769b6-c8a6-11e7-9595-20bcc55828a3.png)
So how should I resolve this error?

**Comment by mtojo** [comment]
You should process TypeScript before `rollup-plugin-stylus-css-modules`.

## Minimum example

### Input

`rollup.config.js`:

```js
import stylusCssModules from 'rollup-plugin-stylus-css-modules';
import typescript from 'rollup-plugin-typescript';

export default {
  dest: 'index.js',
  entry: 'index.ts',
  format: 'iife',
  plugins: [
    typescript(),
    stylusCssModules({
      output: 'index.css'
    })
  ]
}
```

`index.ts`:

```typescript
import styles from './index.styl';
console.log(styles.foo);
```

`index.styl`:

```stylus
.foo
  color: red;
```

### Output

`index.js`:

```js
(function () {
'use strict';

var styles = {"foo":"_index__foo"};

console.log(styles.foo);

}());
```

`index.css`:

```css
._index__foo {
  color: #f00;
}
```

**Comment by B1anker** [comment]
thank you, it works!

**Comment by B1anker** [comment]
But I have another problem when I'm using this plugin, I must add the className on the parent node, so the child can patch it's style.
For exmaple:
`index.styl`：
```styl
.parent
  .child
     background: #333
```
`typescript`：
```typescript
import style from './index.styl'
// don't work
child.className = style.child
// works
parent.className = style.parent
child.className = style.child
```

**Comment by mtojo** [comment]
That Stylus code will output the following CSS:
```css
._index__parent ._index__child {
  background: #333;
}
```
This should apply to HTML like:
```html
<div class="_index__parent">
  <div class="_index__child">
  </div>
</div>
```
The `_index__child` class cannot be used alone.

**Comment by mtojo** [comment]
I tested a similar CSS using postcss and postcss-modules ([link](https://github.com/egoist/rollup-plugin-postcss#use-with-css-modules)).

`rollup.config.js`:

```js
import typescript from 'rollup-plugin-typescript';
import postcss from 'rollup-plugin-postcss';
import postcssModules from 'postcss-modules';

const cssExportMap = {};

export default {
  dest: 'index.js',
  entry: 'index.ts',
  format: 'iife',
  plugins: [
    typescript(),
    postcss({
      plugins: [
        postcssModules({
          getJSON(id, exportTokens) {
            cssExportMap[id] = exportTokens;
          }
        })
      ],
      getExportNamed: false,
      getExport(id) {
        return cssExportMap[id];
      }
    })
  ]
}
```

`index.ts`:

```typescript
import styles from './index.css';
console.log(styles);
```

`index.css`:

```css
.parent .child {
  background: #333;
}
```

Result:

```bash
$ rollup -c && node index.js
{ parent: '_parent_yywr6_1', child: '_child_yywr6_1' }
```

This behavior is almost same with `rollup-plugin-stylus-css-modules`.

**Comment by B1anker** [comment]
So how should I use global css in this case?
Because all the className are converted to the module-like name.
Sometimes we need to reset the css in our projects.

**Comment by mtojo** [comment]
In that case, it's better to simply import using the `link` element on HTML without using CSS modules.

**Comment by B1anker** [comment]
Well...
Anyway, thanks.

**Comment by B1anker** [comment]
Hey, did you publish it in npm?
